In [54]:
import pandas as pd
import random

In [29]:
product_details = pd.read_csv('data/input_data_to_process/product_level_shipment_details_table.csv')
removal_details = pd.read_csv("data/input_data_to_process/removal_order_details_table.csv")
current_stock = pd.read_csv("data/input_data_to_process/current_stock_details_table.csv")
order = pd.read_csv("data/input_data_to_process/order_details_table.csv")

In [53]:
for shp_index, shp_row in product_details.iterrows():
    print(product_details.iat[shp_index,2])

7GDMQCI9KP
RZCVBPAUWU
4PRTSJVE8WE

In [28]:
print(len(order))
total_bytes = order.memory_usage(deep=True).sum()
print(f"Total Size: {total_bytes} bytes")

15
Total Size: 2618 bytes

In [18]:
def gen_one_id_data(item):
    order_df = pd.read_csv("data/input_data_to_process/order_details_table.csv")
    order_df = order_df[order_df["product_code"] == item]
    yield order_df

In [24]:
for i in ['7GDMQCI9KP','RZCVBPAUWU']:
    df = gen_one_id_data(i)

In [26]:
next(df)

StopIteration:

In [108]:
product_details

,shipment_date,shipment_id,product_code,shipped_quantity,received_quantity,order,removal,current_stock
0,2026-01-01,HFV3O0DJS0JTXRC,7GDMQCI9KP,100,100,0,0,0
1,2026-01-01,HFV3O0DJS0JTXRC,RZCVBPAUWU,120,120,0,0,0

In [109]:
for row in product_details.iterrows():
    print(row[1][5])

0
0

In [110]:
removal_details

  removal_date removal_id product_code  removal_quantity
0   2026-01-04        rm1   7GDMQCI9KP                 2
1   2026-01-05        rm2   RZCVBPAUWU                 1
2   2026-01-06        rm3   RZCVBPAUWU                 1

In [111]:
for index ,row in removal_details.iterrows():
    print(removal_details.iat[index,0])

2026-01-04
2026-01-05
2026-01-06

In [112]:
current_stock

  product_code  stock_available
0   7GDMQCI9KP              100
1   RZCVBPAUWU              120

In [113]:
print(current_stock.last_valid_index())

1

In [114]:
print(order['shipment_id_mapped'].first_valid_index()), print(order['shipment_id_mapped'].last_valid_index())

None
None

(None, None)

In [115]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_date          50 non-null     object
 1   order_id            50 non-null     int64
 2   product_code        50 non-null     object
 3   sale                50 non-null     int64
 4   quantity            50 non-null     int64
 5   shipment_id_mapped  0 non-null      float64
dtypes: float64(1), int64(3), object(2)
memory usage: 2.5+ KB

In [116]:
x = tuple((1,2,3,4))
a, b, c, d = x

In [117]:
a, b, c, d

(1, 2, 3, 4)

In [118]:
order.head(5)

   order_date  order_id product_code  sale  quantity  shipment_id_mapped
0  2026-01-06      1001   RZCVBPAUWU   142         4                 NaN
1  2026-01-10      1002   7GDMQCI9KP   400         1                 NaN
2  2026-01-12      1003   7GDMQCI9KP    65         2                 NaN
3  2026-01-06      1004   RZCVBPAUWU   354         1                 NaN
4  2026-01-09      1005   7GDMQCI9KP    16         4                 NaN

In [123]:
x = order.head(10)
for index, row in x.iterrows():
    x.iat[index,5] = "abc" 

x

   order_date  order_id product_code  sale  quantity shipment_id_mapped
0  2026-01-06      1001   RZCVBPAUWU   142         4                abc
1  2026-01-10      1002   7GDMQCI9KP   400         1                abc
2  2026-01-12      1003   7GDMQCI9KP    65         2                abc
3  2026-01-06      1004   RZCVBPAUWU   354         1                abc
4  2026-01-09      1005   7GDMQCI9KP    16         4                abc
5  2026-01-12      1006   RZCVBPAUWU   258         4                abc
6  2026-01-06      1007   7GDMQCI9KP   437         2                abc
7  2026-01-11      1008   RZCVBPAUWU   223         2                abc
8  2026-01-14      1009   RZCVBPAUWU   127         3                abc
9  2026-01-11      1010   RZCVBPAUWU   413         1                abc

In [ ]:
df1 = pd.DataFrame({'A':[1,2,3], 'B': ['w', 'x', 'y']})
df2 = pd.DataFrame({'A':[11,22,33], 'B': ['a', 'b', 'c']})
df3 = pd.DataFrame({'A':[111,222,333], 'B': ['p', 'q', 'r']})
df4 = pd.DataFrame({'A':[1111,2222,3333], 'B': ['m', 'n', 'o']})

lst = [df1, df2, df3, df4]
# 1. Combine them vertically
combined = pd.concat([df1, df2])
combined

    A  B
0   1  w
1   2  x
2   3  y
0  11  a
1  22  b
2  33  c

In [59]:
df1 = pd.DataFrame({'A':[1,2,3], 'B': ['w', 'x', 'y']})
df2 = pd.DataFrame({'A':[11,22,33], 'B': ['a', 'b', 'c']})
df3 = pd.DataFrame({'A':[111,222,333], 'B': ['p', 'q', 'r']})
df4 = pd.DataFrame({'A':[1111,2222,3333], 'B': ['m', 'n', 'o']})

lst = [df1, df2, df3, df4]

combined = pd.concat([i for i in lst])
combined

      A  B
0     1  w
1     2  x
2     3  y
0    11  a
1    22  b
2    33  c
0   111  p
1   222  q
2   333  r
0  1111  m
1  2222  n
2  3333  o

In [5]:
combined.drop(combined.index, inplace=True)
combined

Empty DataFrame
Columns: [A, B]
Index: []

In [6]:
import sys

for path in sys.path:
    print(path)

c:\Users\vishw\Desktop\DE Project\FD_Inventory_Reconciliation_Project
c:\Users\vishw\anaconda3\python310.zip
c:\Users\vishw\anaconda3\DLLs
c:\Users\vishw\anaconda3\lib
c:\Users\vishw\anaconda3

c:\Users\vishw\anaconda3\lib\site-packages
c:\Users\vishw\anaconda3\lib\site-packages\win32
c:\Users\vishw\anaconda3\lib\site-packages\win32\lib
c:\Users\vishw\anaconda3\lib\site-packages\Pythonwin

In [68]:
L1 = []
if L1 is None:
    print('Yes')
else:
    print('No')

No

In [69]:
L1 = [1,2,3,4]
if L1 is None:
    print('Yes')
else:
    print('No')

No

In [78]:
L1 = []
if len(L1) > 0:
    print('Yes')
else:
    print('No')

No